### ISSUE TITLE
Confun_eglif neuron index

### ISSUE THREAD

**Issue by Massimogri** [AliceGem/E-GLIF#2]
https://github.com/AliceGem/E-GLIF/blob/3beeb3d595d95cb77e4a91d3921639d27a206701/optimMATLAB/confun_eglif.m#L14

While changing the constraints for the dcn glycinergic, I realized that the inhibitory current in this line (`Iin`) is actually a vector of 2 elements, since in the "main_optimization" function we defined the inhibitory current as a vector of values each referring to a different neuron type.
Thus, it should be modified as `Iin(neu_ind)`, right?

Same subject for lines 26 and 27: `Vinh_ss(neu_ind)`

**Comment by AliceGem** [comment]
```
% Stimolazione hyp     
Iinh = [-24.0];       
Vinh_min = [-125];      
Vinh_ss = [-115];
```


I have this in the main, so only one element in the `Iinh` and it's weird it's not giving an error with 2 elements. But if you have modified it, yes it has to be changed either inside the `confun `function or in the argument given to that function in the `main `file.

**Comment by Massimogri** [comment]
Ok perfect! 
Actually it didn't give an error because the output was the mean value of the 2 results.
